@url = http://localhost:5013
@typeName = test_first_name
@addressId = 22ba05e2-fdca-4c7d-9f9b-30d4bff5129c

@eventId = b5df9646-2c4c-4afa-a878-5a2289805e4c


###
POST {{url}}/events
Content-Type: application/json

{
    "eventNumber": "string",
    "eventTypeName": "{{typeName}}"
}


###
POST {{url}}/events/add-event
Content-Type: application/json

{
    "typeName": "{{typeName}}"
}

###
GET {{url}}/events/{{eventId}}

###
GET {{url}}/events

#Addresses
###
POST {{url}}/addresses/add-address
Content-Type: application/json

{
    "url": "http://localhost:5154/test-one",
    "eventTypeName": "{{typeName}}"
}

###
POST {{url}}/addresses/add-address
Content-Type: application/json

{
    "url": "http://localhost:5154/test-two",
    "eventTypeName": "{{typeName}}"
}

###
GET {{url}}/addresses/{{addressId}}

###
GET {{url}}/addresses

###
DELETE {{url}}/addresses/{{addressId}}
